(function(){
  const style=document.createElement('style');style.textContent=`
    .gym-live-status{position:relative;z-index:4;display:inline-flex;align-items:center;gap:10px;margin-bottom:4px;padding:9px 13px;border:1px solid rgba(255,255,255,.12);background:rgba(5,5,5,.55);backdrop-filter:blur(12px);border-radius:999px;text-transform:uppercase;letter-spacing:.12em}.gym-live-status small{display:block;color:#777;font-size:7px;letter-spacing:.18em}.gym-live-status b{display:inline-block;font-size:12px;margin-right:7px}.gym-live-status em{font-style:normal;color:#999;font-size:9px}.live-dot{width:8px;height:8px;border-radius:50%;background:#aaa;box-shadow:0 0 12px currentColor}.gym-live-status.busy .live-dot{background:#ff1616;color:#ff1616}.gym-live-status.medium .live-dot{background:#f3b21b;color:#f3b21b}.gym-live-status.quiet .live-dot{background:#42d17a;color:#42d17a}
    .offers-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:45px}.exclusive-card{border:1px solid var(--line);background:linear-gradient(145deg,#121212,#080808);overflow:hidden;position:relative}.offer-image{aspect-ratio:1.5;overflow:hidden;background:#0b0b0b}.offer-image img{width:100%;height:100%;object-fit:cover;display:block;transition:.5s var(--ease)}.exclusive-card:hover .offer-image img{transform:scale(1.04)}.offer-body{padding:22px}.offer-badge{display:inline-block;color:#fff;background:var(--red);padding:6px 8px;font-size:8px;font-weight:900;letter-spacing:.14em}.offer-body h3{font:900 34px Anton;margin:16px 0 8px}.offer-body p{color:#888;font-size:11px;line-height:1.7;min-height:38px}.offer-meta{display:flex;align-items:baseline;gap:10px;margin-top:16px}.offer-price{font:900 34px Anton;color:var(--red)}.offer-price small{font:900 10px Inter}.offer-old{text-decoration:line-through;color:#555;font-size:11px}.offer-expiry{color:#555;font-size:9px;letter-spacing:.1em;text-transform:uppercase}@media(max-width:900px){.offers-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.gym-live-status{margin-top:5px}.offers-grid{grid-template-columns:1fr}.offer-body h3{font-size:30px}}
  `;document.head.appendChild(style);
  const statusMap={quiet:{label:'QUIET',ar:'هادي',className:'quiet'},medium:{label:'MEDIUM',ar:'متوسط',className:'medium'},busy:{label:'BUSY',ar:'زحمة',className:'busy'}};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const asset=u=>u+(u.includes('?')?'&':'?')+'v='+Date.now();
  function statusHtml(status){const s=statusMap[status]||statusMap.medium;return `<div class="gym-live-status ${s.className}"><span class="live-dot"></span><span><small>GYM STATUS</small><b>${s.label}</b><em>${s.ar}</em></span></div>`}
  function offerCard(o){const image=o.image?`<div class="offer-image"><img src="${esc(asset(o.image))}" alt="${esc(o.title)}" loading="lazy"></div>`:'';const price=o.price?`<div class="offer-price">${esc(o.price)}<small> LE</small></div>`:'';const old=o.oldPrice?`<div class="offer-old">${esc(o.oldPrice)} LE</div>`:'';return `<article class="exclusive-card">${image}<div class="offer-body"><span class="offer-badge">EXCLUSIVE OFFER</span><h3>${esc(o.title)}</h3><p>${esc(o.description||'Limited-time offer from FITNESS GYM.')}</p><div class="offer-meta">${price}${old}</div>${o.expiresAt?`<small class="offer-expiry">Until ${esc(o.expiresAt)}</small>`:''}</div></article>`}
  async function boot(){try{const res=await fetch('/api/site-data',{cache:'no-store'});if(!res.ok)return;const data=await res.json();const hero=document.querySelector('.hero-copy');if(hero&&!document.querySelector('.gym-live-status'))hero.insertAdjacentHTML('afterbegin',statusHtml(data.status));const gallery=document.querySelector('.gallery-grid');if(gallery&&Array.isArray(data.gallery))gallery.innerHTML=data.gallery.map((g,i)=>`<figure class="gallery-card"><img src="${esc(asset(g.image))}" alt="${esc(g.title)}" loading="${i<2?'eager':'lazy'}"><span>${esc(g.title)}</span></figure>`).join('');if(Array.isArray(data.offers)&&data.offers.length){const memberships=document.getElementById('memberships');if(memberships&&!document.getElementById('exclusive-offers')){const section=document.createElement('section');section.id='exclusive-offers';section.className='fg-section';section.innerHTML=`<div class="reveal"><div class="fg-kicker">05.5 / EXCLUSIVE</div><h2 class="fg-heading">EXCLUSIVE<br><em>OFFERS.</em></h2></div><div class="offers-grid reveal">${data.offers.filter(o=>o.active!==false).map(offerCard).join('')}</div>`;memberships.before(section);requestAnimationFrame(()=>section.querySelectorAll('.reveal').forEach(e=>e.classList.add('in'));)}}}catch(e){console.warn('CMS data unavailable',e)}}boot();
})();
