(function(){
  const WA='201033659722';
  const facebookUrl='https://www.facebook.com/share/14sgcfbPFvf/?mibextid=wwXIfr';
  const plans=[
    {key:'prime',name:'Prime',frequency:['2 DAYS WEEKLY','مرتين في الأسبوع'],prices:[350,650,850,1500,2500]},
    {key:'matrix',name:'Matrix',frequency:['3 DAYS WEEKLY','3 أيام في الأسبوع'],prices:[450,850,1100,1900,3200]},
    {key:'elite',name:'Elite',frequency:['4 DAYS WEEKLY','4 أيام في الأسبوع'],prices:[500,900,1200,2100,3600]},
    {key:'legend',name:'Legend',frequency:['5 DAYS WEEKLY','5 أيام في الأسبوع'],prices:[550,1000,1300,2300,4000]},
    {key:'unlimited',name:'Unlimited',frequency:['EVERY DAY · ∞ SESSIONS','كل يوم · تمرين براحتك'],prices:[600,1100,1450,2500,4300]}
  ];
  const periods=[['1 Month','شهر'],['2 Months','شهرين'],['3 Months','3 شهور'],['6 Months','6 شهور'],['12 Months','سنة']];
  const translations={
    ar:{
      nav:['التجربة','مواعيدنا','العضويات','الجاليري'],join:'يلا اشترك',eyebrow:'FITNESS GYM CLUB · الفيوم',heroTitle:'اتمرّن<br><span>بشكل مختلف.</span>',heroText:'عايز تتمرّن بجد؟ تعالى جرّب مكان معمول عشان تطوّر نفسك، تقوّي جسمك وتكسر روتينك. شوف الجيم واختار العضوية اللي ماشية معاك.',explore:'شوف العضويات ←',call:'كلمنا 01033659722',heroIndex:'يلا ابدأ التجربة',
      marquee1:'اتمرّن بقوة <b>///</b> حافظ على الاستمرارية <b>///</b> طوّر نفسك <b>///</b> FITNESS GYM CLUB <b>///</b> اتمرّن بقوة <b>///</b> حافظ على الاستمرارية <b>///</b> طوّر نفسك <b>///</b> FITNESS GYM CLUB <b>///</b>',
      expKicker:'02 / التجربة',expHeading:'مش مجرد<br><em>جيم.</em>',expCopy:'هنا التمرين له شكل تاني. مكان حقيقي، معدات قوية وجو يخليك عايز تنزل تتمرّن وتكسر أرقامك كل مرة.',stats:['دخول الرجال','مواعيد السيدات','مستويات العضوية'],galleryKicker:'03 / المكان',galleryHeading:'شوف<br><em>الجيم على حقيقته.</em>',galleryNote:'صور حقيقية من الجيم · شوف المكان والمعدات قبل ما تيجي.',
      gallery:['منطقة التمرين الرئيسية','منطقة التدريب','منطقة المرايا','الأوزان الحرة','حامل الدمبلز','منطقة المعدات','محطة الكابل','مدخل الجيم','منطقة القوة','أرضية التدريب','أجهزة القوة','واجهة الجيم','المنطقة الداخلية','منطقة الأجهزة','المنطقة الوظيفية','منطقة الكارديو','الاستقبال'],
      hoursKicker:'04 / مواعيدنا',hoursHeading:'تمرّن في<br><em>وقتك.</em>',men:'رجال',women:'سيدات',daily:'يوميًا',menText:'مفتوح ليك طول اليوم. تعالى في الوقت اللي يناسبك وخلّي التمرين على مزاجك.',womenText:'مواعيد مخصوص للسيدات عشان تتمرّني براحتك وتلعبي على هدفك.',
      marquee2:'انضباط <b>///</b> قوة <b>///</b> استمرارية <b>///</b> تطور <b>///</b> انضباط <b>///</b> قوة <b>///</b> استمرارية <b>///</b> تطور <b>///</b>',
      membershipKicker:'05 / العضويات',membershipHeading:'اختار<br><em>نظامك.</em>',membershipCopy:'اختار الفئة اللي مناسبة لطريقة تمرينك، وبعدها اختار المدة اللي على مزاجك. دوس تواصل وهنكمل معاك على الواتساب.',choose:'اختار الفئة',duration:'اختار مدة الاشتراك',contact:'تواصل على واتساب',selected:'مختار',
      finalKicker:'06 / جاهز؟',finalHeading:'يلا<br><span>نبدأ.</span>',finalText:'عندك سؤال عن العضويات أو المواعيد؟ كلمنا على طول وخد كل التفاصيل.',finalButton:'كلمنا واتساب 01033659722 ←',hoursLabel:'مواعيدنا',contactLabel:'كلمنا',whatsapp:'واتساب',footer:'© FITNESS GYM CLUB · يلا نتمرّن.',status:'حالة الجيم',exclusive:'عرض جامد',until:'لحد',limited:'عرض لفترة محدودة من FITNESS GYM.'
    },
    en:{
      nav:['Experience','Hours','Memberships','Gallery'],join:'Join Now',eyebrow:'FITNESS GYM CLUB · FAYOUM',heroTitle:'TRAIN<br><span>DIFFERENT.</span>',heroText:'Train in a real space built for discipline, strength and consistency. Explore the club, see the facility and choose the membership that fits your routine.',explore:'Explore Memberships →',call:'Call 01033659722',heroIndex:'ENTER THE EXPERIENCE',
      marquee1:'TRAIN HARD <b>///</b> STAY CONSISTENT <b>///</b> BUILD YOURSELF <b>///</b> FITNESS GYM CLUB <b>///</b> TRAIN HARD <b>///</b> STAY CONSISTENT <b>///</b> BUILD YOURSELF <b>///</b> FITNESS GYM CLUB <b>///</b>',
      expKicker:'02 / THE EXPERIENCE',expHeading:'NOT JUST<br><em>A GYM.</em>',expCopy:'A visual experience built around the real FITNESS GYM space. The photography is integrated into the layout to showcase the facility and equipment clearly.',stats:["Men's access","Women's hours","Membership levels"],galleryKicker:'03 / THE SPACE',galleryHeading:'SEE THE<br><em>REAL GYM.</em>',galleryNote:'Real club photography · All supplied images integrated into the experience.',
      gallery:['Main training floor','Training area','Mirror zone','Free weights','Dumbbell rack','Equipment floor','Cable station','Club entrance','Strength zone','Training floor','Strength machine','Club exterior','Interior','Machine zone','Functional area','Cardio area','Reception'],
      hoursKicker:'04 / OPENING HOURS',hoursHeading:'YOUR TIME.<br><em>YOUR RULES.</em>',men:'MEN',women:'WOMEN',daily:'DAILY',menText:'Open every day, all day.',womenText:'Women-only training hours.',
      marquee2:'DISCIPLINE <b>///</b> STRENGTH <b>///</b> CONSISTENCY <b>///</b> PROGRESS <b>///</b> DISCIPLINE <b>///</b> STRENGTH <b>///</b> CONSISTENCY <b>///</b> PROGRESS <b>///</b>',
      membershipKicker:'05 / MEMBERSHIPS',membershipHeading:'CHOOSE YOUR<br><em>LEVEL.</em>',membershipCopy:'Pick the membership level that fits your training routine, then choose your duration. Hit WhatsApp and we will take it from there.',choose:'CHOOSE A LEVEL',duration:'CHOOSE YOUR DURATION',contact:'Contact on WhatsApp',selected:'SELECTED',
      finalKicker:'06 / READY?',finalHeading:'MAKE<br><span>THE MOVE.</span>',finalText:'Questions about memberships, hours or joining? Talk directly to FITNESS GYM.',finalButton:'WhatsApp 01033659722 →',hoursLabel:'HOURS',contactLabel:'CONTACT',whatsapp:'WhatsApp',footer:'© FITNESS GYM CLUB · All rights reserved.',status:'GYM STATUS',exclusive:'EXCLUSIVE OFFER',until:'Until',limited:'Limited-time offer from FITNESS GYM.'
    }
  };

  const statusMap={quiet:{label:'QUIET',ar:'هادي',className:'quiet'},medium:{label:'MEDIUM',ar:'متوسط',className:'medium'},busy:{label:'BUSY',ar:'زحمة',className:'busy'}};
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const msg=(plan,period,price,ar)=>ar?`هاي Fitness Gym، أنا عايز أشترك في عضوية ${plan.name} لمدة ${period[1]} بسعر ${price} جنيه. ممكن أعرف التفاصيل؟`:`Hello FITNESS GYM, I'd like to join the ${plan.name} membership for ${period[0]} at ${price} LE. Please send me the details.`;
  const wa=(text)=>`https://wa.me/${WA}?text=${encodeURIComponent(text)}`;

  function injectStyle(){
    if(document.getElementById('fitness-membership-style'))return;
    const style=document.createElement('style');style.id='fitness-membership-style';style.textContent=`
      .membership-picker{margin-top:48px}.membership-picker.plans{display:block!important;grid-template-columns:none!important;width:100%!important;min-width:0!important}.membership-picker-head{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:18px}.membership-picker-label{font-size:9px;color:#777;letter-spacing:.16em;text-transform:uppercase}.membership-tabs{display:flex;gap:8px;overflow-x:auto;padding:4px 2px 12px;scrollbar-width:none}.membership-tabs::-webkit-scrollbar{display:none}.membership-tab{flex:1;min-width:145px;border:1px solid var(--line);background:linear-gradient(145deg,#121212,#080808);color:#888;padding:18px 16px;text-align:left;cursor:pointer;transition:.3s var(--ease);position:relative;overflow:hidden}.membership-tab strong{display:block;font:900 27px Anton;color:#eee;text-transform:uppercase}.membership-tab small{display:block;color:#666;font-size:8px;letter-spacing:.1em;margin-top:7px}.membership-tab.active{border-color:var(--red);background:linear-gradient(145deg,rgba(255,22,22,.18),#080808);box-shadow:0 14px 35px rgba(0,0,0,.28)}.membership-tab.active strong{color:#fff}.membership-tab.active small{color:#ff5b5b}.duration-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-top:16px;width:100%}.duration-card{min-height:265px;border:1px solid var(--line);background:linear-gradient(150deg,#111,#070707);padding:22px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;transition:.35s var(--ease)}.duration-card::before{content:"";position:absolute;width:150px;height:150px;border-radius:50%;background:var(--red);filter:blur(75px);opacity:.06;right:-80px;top:-80px}.duration-card:hover{transform:translateY(-7px);border-color:rgba(255,22,22,.55)}.duration-card .duration-number{font-size:8px;color:#555;letter-spacing:.16em}.duration-card h4{font:900 30px Anton;margin:12px 0 4px;color:#fff}.duration-card .price{font:900 40px Anton;color:var(--red);line-height:1}.duration-card .price small{font:900 9px Inter;color:#888;letter-spacing:.08em}.duration-card .plan-frequency{color:#777;font-size:9px;letter-spacing:.1em;text-transform:uppercase;margin-top:8px}.duration-card .wa-choice{display:flex;align-items:center;justify-content:center;gap:8px;border:1px solid var(--line);color:#fff;text-decoration:none;padding:12px 10px;font-size:9px;font-weight:900;letter-spacing:.1em;text-transform:uppercase;transition:.25s}.duration-card .wa-choice:hover{background:var(--red);border-color:var(--red)}.duration-card.selected-card{border-color:rgba(255,22,22,.7);box-shadow:0 20px 55px rgba(0,0,0,.35),0 0 35px rgba(255,22,22,.06)}
      .language-switcher{display:inline-flex;align-items:center;gap:0;margin-left:auto;margin-right:18px;padding:3px;border:1px solid rgba(255,255,255,.14);background:rgba(10,10,10,.72);backdrop-filter:blur(14px);border-radius:999px;box-shadow:0 8px 30px rgba(0,0,0,.2)}.language-switcher button{border:0;background:transparent;color:#777;min-width:42px;height:30px;padding:0 11px;border-radius:999px;font:800 10px Inter,sans-serif;letter-spacing:.08em;cursor:pointer;transition:.25s ease}.language-switcher button:hover{color:#fff}.language-switcher button.active{background:var(--red);color:#fff;box-shadow:0 4px 15px rgba(255,22,22,.22)}.language-switcher .lang-divider{width:1px;height:15px;background:rgba(255,255,255,.12)}
      .floating-fb{position:fixed;z-index:120;right:22px;bottom:92px;width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#1877F2;color:#fff;box-shadow:0 12px 40px rgba(24,119,242,.28);transition:.35s var(--ease);text-decoration:none}.floating-fb:hover{transform:scale(1.08) translateY(-4px)}.floating-fb svg{width:28px;height:28px;fill:currentColor}
      html.lang-ar body{font-family:Inter,"Arial",sans-serif}html.lang-ar .nav-links{direction:rtl}html.lang-ar .hero-copy{text-align:right;margin-left:0;margin-right:7vw}html.lang-ar .hero-copy p{margin-right:0;margin-left:auto}html.lang-ar .hero-index{right:auto;left:5vw}html.lang-ar .hero-index b{margin-right:0;margin-left:8px}html.lang-ar .fg-actions{justify-content:flex-start;flex-direction:row-reverse}html.lang-ar .space-intro{direction:rtl}html.lang-ar .space-copy{margin-right:0;margin-left:auto}html.lang-ar .stats{direction:rtl}html.lang-ar .gallery-grid{direction:ltr}html.lang-ar .gallery-card span{left:auto;right:16px;text-align:right;direction:rtl}html.lang-ar .membership-head{direction:rtl}html.lang-ar .membership-picker{direction:rtl}html.lang-ar .membership-picker-head{text-align:right}html.lang-ar .membership-tab{text-align:right}html.lang-ar .duration-card{text-align:right}html.lang-ar .duration-card .wa-choice{direction:rtl}html.lang-ar .final-cta{direction:rtl}html.lang-ar .footer{direction:rtl}html.lang-ar .footer-bottom{text-align:right}
      @media(max-width:1050px){.duration-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.membership-tabs{gap:7px}.membership-tab{min-width:155px}.language-switcher{margin-left:auto;margin-right:12px}.site-nav{gap:8px}}
      @media(max-width:620px){.membership-picker{margin-top:32px}.membership-picker-head{display:block;margin-bottom:10px}.membership-tabs{margin-inline:-2px}.membership-tab{min-width:125px;padding:14px 12px}.membership-tab strong{font-size:23px}.duration-grid{grid-template-columns:1fr;gap:9px}.duration-card{min-height:210px;padding:20px}.duration-card h4{font-size:28px}.duration-card .price{font-size:38px}.language-switcher{margin-left:auto;margin-right:7px;padding:2px}.language-switcher button{min-width:35px;height:28px;padding:0 8px;font-size:9px}.language-switcher .lang-divider{height:13px}.nav-cta{white-space:nowrap}.hero-copy{margin-right:0!important}.hero-index{left:18px!important;right:auto!important}.floating-fb{right:16px;bottom:84px;width:52px;height:52px}.floating-fb svg{width:25px;height:25px}}
    `;document.head.appendChild(style);
  }

  function ensureFacebook(){if(document.querySelector('.floating-fb'))return;const a=document.createElement('a');a.className='floating-fb';a.href=facebookUrl;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','Facebook FITNESS GYM');a.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.5 8.5V7c0-.7.3-1 1-1h1.5V3h-2.5C10.8 3 9 4.8 9 7.4v1.1H6.5v3H9V21h3.5v-9.5H15l.5-3h-3.5z"/></svg>';document.body.appendChild(a)}

  function ensureLanguage(){
    if(document.querySelector('.language-switcher'))return;
    const nav=document.querySelector('.site-nav');if(!nav)return;const cta=nav.querySelector('.nav-cta');const wrap=document.createElement('div');wrap.className='language-switcher';wrap.innerHTML='<button type="button" data-lang="ar">AR</button><span class="lang-divider"></span><button type="button" data-lang="en">EN</button>';wrap.addEventListener('click',e=>{const b=e.target.closest('button[data-lang]');if(b)setLanguage(b.dataset.lang)});if(cta)nav.insertBefore(wrap,cta);else nav.appendChild(wrap)
  }

  function renderMemberships(lang){
    const host=document.querySelector('#memberships .plans');if(!host)return;
    const t=translations[lang];
    let active=host.dataset.activePlan||'unlimited';
    if(!plans.some(p=>p.key===active))active='unlimited';
    host.className='membership-picker plans';
    host.innerHTML=`<div class="membership-picker-head"><div><div class="membership-picker-label">${esc(t.choose)}</div></div><div class="membership-picker-label">${esc(t.duration)}</div></div><div class="membership-tabs">${plans.map(p=>`<button type="button" class="membership-tab ${p.key===active?'active':''}" data-plan="${p.key}"><strong>${p.name}</strong><small>${esc(p.frequency[lang==='ar'?1:0])}</small></button>`).join('')}</div><div class="duration-grid">${durationCards(active,lang)}</div>`;
    host.querySelectorAll('.membership-tab').forEach(btn=>btn.addEventListener('click',()=>{host.dataset.activePlan=btn.dataset.plan;renderMemberships(lang)}));
    host.querySelectorAll('.wa-choice').forEach(btn=>btn.addEventListener('click',()=>{btn.closest('.duration-card')?.classList.add('selected-card')}));
  }

  function durationCards(key,lang){
    const p=plans.find(x=>x.key===key)||plans[4];
    return periods.map((period,i)=>{const price=p.prices[i];return `<article class="duration-card"><div><span class="duration-number">0${i+1} / ${esc(p.name.toUpperCase())}</span><h4>${esc(period[lang==='ar'?1:0])}</h4><div class="price">${price}<small> LE</small></div><div class="plan-frequency">${esc(p.frequency[lang==='ar'?1:0])}</div></div><a class="wa-choice" href="${wa(msg(p,period,price,lang==='ar'))}" target="_blank" rel="noopener">${esc(translations[lang].contact)} →</a></article>`}).join('');
  }

  function setLanguage(lang){
    const next=lang==='en'?'en':'ar';localStorage.setItem('fitness-gym-language',next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';document.documentElement.classList.toggle('lang-ar',next==='ar');document.body.classList.toggle('lang-ar',next==='ar');
    const t=translations[next];
    document.querySelectorAll('.nav-links a').forEach((el,i)=>{if(t.nav[i])el.textContent=t.nav[i]});
    const set=(sel,val)=>{const el=document.querySelector(sel);if(el)el.innerHTML=val};
    set('.nav-cta',t.join);set('.hero-copy .fg-eyebrow',t.eyebrow);set('.hero-copy h1',t.heroTitle);set('.hero-copy p',t.heroText);set('.hero-copy .fg-actions .primary',t.explore);set('.hero-copy .fg-actions a:not(.primary)',t.call);set('.hero-index',`<b>01</b> ${t.heroIndex}`);
    const marquees=document.querySelectorAll('.fg-marquee-track');if(marquees[0])marquees[0].innerHTML=t.marquee1;if(marquees[1])marquees[1].innerHTML=t.marquee2;
    set('#experience .fg-kicker',t.expKicker);set('#experience .fg-heading',t.expHeading);set('#experience .space-copy',t.expCopy);document.querySelectorAll('.stats .stat span').forEach((el,i)=>{if(t.stats[i])el.textContent=t.stats[i]});
    set('#gallery .fg-kicker',t.galleryKicker);set('#gallery .fg-heading',t.galleryHeading);set('.gallery-note',t.galleryNote);document.querySelectorAll('.gallery-card span').forEach((el,i)=>{if(t.gallery[i])el.textContent=t.gallery[i]});
    set('#hours .fg-kicker',t.hoursKicker);set('#hours .fg-heading',t.hoursHeading);const cards=document.querySelectorAll('.hour-card');if(cards[0]){cards[0].querySelector('.fg-kicker').textContent=t.men;cards[0].querySelector('p').textContent=t.menText}if(cards[1]){cards[1].querySelector('.fg-kicker').textContent=t.women;cards[1].querySelector('h3').textContent=t.daily;cards[1].querySelector('p').textContent=t.womenText}
    set('#memberships .membership-head .fg-kicker',t.membershipKicker);set('#memberships .membership-head .fg-heading',t.membershipHeading);set('#memberships .membership-head p',t.membershipCopy);renderMemberships(next);
    set('.final-cta .fg-kicker',t.finalKicker);set('.final-cta h2',t.finalHeading);set('.final-cta p',t.finalText);set('.final-cta .fg-btn',t.finalButton);
    const footerPs=document.querySelectorAll('.footer p');if(footerPs[1])footerPs[1].innerHTML=`<strong style="color:#fff">${t.hoursLabel}</strong><br>${t.men} · 24 / 7<br>${t.women} · 8 AM to 10 PM`;if(footerPs[2])footerPs[2].innerHTML=`<strong style="color:#fff">${t.contactLabel}</strong><br><a href="tel:01033659722">01033659722</a><br><a href="https://wa.me/${WA}" target="_blank" rel="noopener">${t.whatsapp}</a>`;const fb=document.querySelector('.footer-bottom');if(fb)fb.textContent=t.footer;
    document.title=next==='en'?'FITNESS GYM — Train Different.':'FITNESS GYM — اتمرّن بشكل مختلف.';const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=next==='en'?'FITNESS GYM Club — premium training in Fayoum. Men 24/7. Women 8 AM to 10 PM.':'FITNESS GYM Club — جيم مميز في الفيوم. الرجال 24/7 والسيدات من 8 صباحًا حتى 10 مساءً.';
    document.querySelectorAll('.language-switcher button').forEach(b=>b.classList.toggle('active',b.dataset.lang===next));
  }

  function statusHtml(status){const s=statusMap[status]||statusMap.medium;return `<div class="gym-live-status ${s.className}"><span class="live-dot"></span><span><small>${translations[document.documentElement.lang==='en'?'en':'ar'].status}</small><b>${document.documentElement.lang==='en'?s.label:s.ar}</b>${document.documentElement.lang==='en'?`<em></em>`:''}</span></div>`}
  function offerCard(o,lang){const t=translations[lang];const image=o.image?`<div class="offer-image"><img src="${esc(o.image)}" alt="${esc(o.title)}" loading="lazy" decoding="async"></div>`:'';return `<article class="exclusive-card">${image}<div class="offer-body"><span class="offer-badge">${t.exclusive}</span><h3>${esc(o.title)}</h3><p>${esc(o.description||t.limited)}</p><div class="offer-meta">${o.price?`<div class="offer-price">${esc(o.price)}<small> LE</small></div>`:''}${o.oldPrice?`<div class="offer-old">${esc(o.oldPrice)} LE</div>`:''}</div>${o.expiresAt?`<small class="offer-expiry">${t.until} ${esc(o.expiresAt)}</small>`:''}</div></article>`}

  function render(data){
    injectStyle();ensureFacebook();ensureLanguage();
    const hero=document.querySelector('.hero-copy');if(hero){const old=hero.querySelector('.gym-live-status');const html=statusHtml(data.status);if(old)old.outerHTML=html;else hero.insertAdjacentHTML('afterbegin',html)}
    const gallery=document.querySelector('.gallery-grid');if(gallery&&Array.isArray(data.gallery)&&data.gallery.length)gallery.innerHTML=data.gallery.map(g=>`<figure class="gallery-card"><img src="${esc(g.image)}" alt="${esc(g.title)}" loading="lazy" decoding="async" fetchpriority="low"><span>${esc(g.title)}</span></figure>`).join('');
    let section=document.getElementById('exclusive-offers');const offers=Array.isArray(data.offers)?data.offers.filter(o=>o.active!==false):[];if(offers.length){const memberships=document.getElementById('memberships');if(!section&&memberships){section=document.createElement('section');section.id='exclusive-offers';section.className='fg-section';section.innerHTML='<div class="reveal"><div class="fg-kicker">05.5 / EXCLUSIVE</div><h2 class="fg-heading">EXCLUSIVE<br><em>OFFERS.</em></h2></div><div class="offers-grid reveal"></div>';memberships.before(section)}if(section){const grid=section.querySelector('.offers-grid');if(grid)grid.innerHTML=offers.map(o=>offerCard(o,document.documentElement.lang==='en'?'en':'ar')).join('');section.querySelectorAll('.reveal').forEach(e=>e.classList.add('in'))}}else if(section)section.remove();
    setLanguage(localStorage.getItem('fitness-gym-language')||'ar');
  }

  let lastSignature='';let requestInFlight=false;
  async function boot(force=false){if(requestInFlight||document.visibilityState==='hidden')return;requestInFlight=true;try{const r=await fetch(`/api/site-data?t=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw new Error(r.status);const data=await r.json();const sig=JSON.stringify(data);if(force||sig!==lastSignature){lastSignature=sig;render(data)}else{ensureFacebook();ensureLanguage()}}catch(e){console.warn('CMS data unavailable',e);injectStyle();ensureFacebook();ensureLanguage();setLanguage(localStorage.getItem('fitness-gym-language')||'ar')}finally{requestInFlight=false}}
  function start(){injectStyle();ensureFacebook();ensureLanguage();setLanguage(localStorage.getItem('fitness-gym-language')||'ar');boot(true);setInterval(()=>boot(),2000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')boot(true)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
